name: Node.js CI/CD

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/*'

env:
  NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
  NGROK_DOMAIN: ${{ secrets.NGROK_DOMAIN }}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run server.js
        run: node server.js